@api_host = https://localhost:7078

POST {{api_host}}/customer/
Accept: application/json
Content-Type: application/json

{
  "CustomerId": "8b311274-10c1-4a41-bbac-e6477e16c800",
  "FullName": "Bahar Ganji",
  "Email": "bahar@tech.com",
  "DateOfBirth": "2010-09-07T00:00:00"
}

###

GET {{api_host}}/customer/8b311274-10c1-4a41-bbac-e6477e16c800
