// <auto-generated/>

using System.Text.Json.Serialization;
using CustomerManagementSystem.Api.Customers.Register;

namespace CustomerManagementSystem.Api.Shared;

[JsonPolymorphic(IgnoreUnrecognizedTypeDiscriminators = true)]
[JsonDerivedType(typeof(CustomerRegistered), nameof(CustomerRegistered))]
public abstract partial record Event { }
